// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class MessagesPigeonCodecReader: FlutterStandardReader {
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Dart -> native. Requests are one-way: the actual state only ever comes
/// back through [WindowFullscreenFlutterApi], because the system can leave
/// fullscreen behind the app's back (green button, Mission Control,
/// Ctrl+Cmd+F, Esc in native fullscreen).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WindowFullscreenHostApi {
  /// The window's actual fullscreen state right now, read directly instead
  /// of assumed — a hot restart resets Dart state, not the window.
  func isFullscreen() throws -> Bool
  /// Requests entering or leaving fullscreen.
  ///
  /// Returns whether a transition was actually started. `false` when one is
  /// already in progress (macOS ignores `toggleFullScreen` mid-animation) or
  /// the window is already in the requested state — in both cases no
  /// [WindowFullscreenFlutterApi.onFullscreenChanged] callback will follow.
  func setFullscreen(fullscreen: Bool) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WindowFullscreenHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WindowFullscreenHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WindowFullscreenHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// The window's actual fullscreen state right now, read directly instead
    /// of assumed — a hot restart resets Dart state, not the window.
    let isFullscreenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.movier_window.WindowFullscreenHostApi.isFullscreen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isFullscreenChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isFullscreen()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isFullscreenChannel.setMessageHandler(nil)
    }
    /// Requests entering or leaving fullscreen.
    ///
    /// Returns whether a transition was actually started. `false` when one is
    /// already in progress (macOS ignores `toggleFullScreen` mid-animation) or
    /// the window is already in the requested state — in both cases no
    /// [WindowFullscreenFlutterApi.onFullscreenChanged] callback will follow.
    let setFullscreenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.movier_window.WindowFullscreenHostApi.setFullscreen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFullscreenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fullscreenArg = args[0] as! Bool
        do {
          let result = try api.setFullscreen(fullscreen: fullscreenArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFullscreenChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart. The only source of truth for the window's fullscreen
/// state, whether the transition was requested by the app or by the system.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WindowFullscreenFlutterApiProtocol {
  func onFullscreenChanged(fullscreen fullscreenArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WindowFullscreenFlutterApi: WindowFullscreenFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onFullscreenChanged(fullscreen fullscreenArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.movier_window.WindowFullscreenFlutterApi.onFullscreenChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([fullscreenArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
