video-formatting:
  multi-presets: false
  presets:
    - name: "1080p"
      resolution:
        width: 1920
        height: 1080
      videoBitrate: 5_000_000
      audioBitrate: 192_000
      videoCodec: "libx264"
      audioCodec: "aac"
      crf: 23
      preset: "medium"
      enabled: true

    - name: "720p"
      resolution:
        width: 1280
        height: 720
      videoBitrate: 2_500_000
      audioBitrate: 128_000
      videoCodec: "libx264"
      audioCodec: "aac"
      crf: 23
      preset: "medium"
      enabled: true

    - name: "480p"
      resolution:
        width: 854
        height: 480
      videoBitrate: 1_000_000
      audioBitrate: 96_000
      videoCodec: "libx264"
      audioCodec: "aac"
      crf: 23
      preset: "medium"
      enabled: true

    - name: "360p"
      resolution:
        width: 460
        height: 360
      videoBitrate: 1_000_000
      audioBitrate: 96_000
      videoCodec: "libx264"
      audioCodec: "aac"
      crf: 20
      preset: "medium"
      enabled: true

  output:
    format: "mp4"
    faststart: true