name: movier
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  l: 5.0.1
  google_fonts: 6.3.2
  dio: 5.9.2
  freezed: 3.2.3
  freezed_annotation: 3.1.0
  json_serializable: 6.11.1
  cached_network_image: 3.4.1
  motor: ^1.1.0
  control: ^0.2.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_android_video: ^1.3.8
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_macos_video: ^1.1.4
  screen_brightness: ^2.1.2
  movier_window:
    path: packages/movier_window

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  build_runner: ^2.13.1

flutter:
  uses-material-design: true
  generate: true
